DROP TABLE Waste CASCADE CONSTRAINTS;
DROP TABLE Logs CASCADE CONSTRAINTS;
DROP TABLE Users CASCADE CONSTRAINTS;
DROP TABLE Placements CASCADE CONSTRAINTS;
DROP TABLE Items CASCADE CONSTRAINTS;
DROP TABLE Containers CASCADE CONSTRAINTS;
DROP TABLE Zones CASCADE CONSTRAINTS;
-- =========================
-- ZONES (already created)
-- =========================
CREATE TABLE Zones (
    zone_id VARCHAR2(20) PRIMARY KEY,
    zone_name VARCHAR2(50)
);

-- =========================
-- CONTAINERS
-- =========================
CREATE TABLE Containers (
    container_id VARCHAR2(20) PRIMARY KEY,
    zone_id VARCHAR2(20),
    width NUMBER,
    depth NUMBER,
    height NUMBER,
    FOREIGN KEY (zone_id) REFERENCES Zones(zone_id)
);

-- =========================
-- ITEMS
-- =========================
CREATE TABLE Items (
    item_id VARCHAR2(20) PRIMARY KEY,
    name VARCHAR2(100),
    width NUMBER,
    depth NUMBER,
    height NUMBER,
    mass NUMBER,
    priority NUMBER,
    expiry_date DATE,
    usage_limit NUMBER,
    preferred_zone VARCHAR2(20)
);

-- =========================
-- PLACEMENTS
-- =========================
CREATE TABLE Placements (
    placement_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id VARCHAR2(20),
    container_id VARCHAR2(20),
    start_width NUMBER,
    start_depth NUMBER,
    start_height NUMBER,
    end_width NUMBER,
    end_depth NUMBER,
    end_height NUMBER,
    FOREIGN KEY (item_id) REFERENCES Items(item_id),
    FOREIGN KEY (container_id) REFERENCES Containers(container_id)
);

-- =========================
-- USERS
-- =========================
CREATE TABLE Users (
    user_id VARCHAR2(20) PRIMARY KEY,
    name VARCHAR2(50)
);

-- =========================
-- LOGS
-- =========================
CREATE TABLE Logs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(20),
    item_id VARCHAR2(20),
    action_type VARCHAR2(20),
    timestamp DATE,
    FOREIGN KEY (user_id) REFERENCES Users(user_id),
    FOREIGN KEY (item_id) REFERENCES Items(item_id)
);

-- =========================
-- WASTE
-- =========================
CREATE TABLE Waste (
    waste_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id VARCHAR2(20),
    reason VARCHAR2(50),
    FOREIGN KEY (item_id) REFERENCES Items(item_id)
);